import type { Metadata } from "next";
import { roboto } from '@/app/fonts';
import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <h1 className="text-4xl font-bold">Women's Super League</h1>
        <div className="flex flex-row gap-2">
          <Link href="/pages/matches">Matches</Link>
          <Link href="/pages/table">Table</Link>
          <Link href="/pages/stats">Stats</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
