
import type { Metadata } from "next";
import { roboto } from '@/app/fonts';
import "./globals.css";
import NavLink from "./components/NavLink/NavLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <h1 className="text-4xl font-bold">Women's Super League</h1>
        <div className="flex flex-row gap-2">
          <NavLink href="/">Overview</NavLink>
          <NavLink href="/pages/matches">Matches</NavLink>
          <NavLink href="/pages/table">Table</NavLink>
          <NavLink href="/pages/stats">Stats</NavLink>

        </div>
        {children}
      </body>
    </html>
  );
}
